### PR TITLE
feat(markuplint-angular-rules): creating package with first rule

### LINKED ISSUE #100: Angular specific rules
Hi.
I'm working on a set of rules for Angular, for example on a linter rule enforcing order of inputs, outputs, etc.

Are you interested in making this a part of this repo and publishing another package?

### PR DESCRIPTION
**Pull request by undsoft**
Resolves #100.

Changes:
1. Adds a new package called `markuplint-angular-rules` with a first rule.
2. Updates main README to be more Angular specific.
3. Disabled a linter rule for .spec files.

Testing:
1. Build new package.
2. Link with `yarn link`
3. Go to an Angular project and link there.
4. Follow readme instructions to enable rule and lint project.

### CODE REVIEW

**Comment by undsoft** [comment]
Things I need help with:
1. I'm not too familiar with changesets and how publishing works.
2. I had issues with build as well. 
If I run build from `packages/markuplint-angular-rules` I can build fine.
If I run build from the root, the build in `lib` file is incomplete for some reason (It's missing index.js). I also get some warnings about circular dependencies.

**Comment by JounQin** [comment]
I'm sorry I'm very busy on business these days, so I cannot offer much help here, in order to not block what you want, maybe you can just 1. publish it on your own repo, 2. help to fix current issues.

**Comment by undsoft** [comment]
That's fine, I can wait. I've already invested time in making it work in this repo.

**Comment by JounQin** [comment]
@undsoft I changed to use snapshot based test at [`977068a` (#101)](https://github.com/un-ts/markuplint/pull/101/commits/977068a89b160b9705a19f35914a0039d1a08272) and changed the packages folder a bit. How do you think so?

**Comment by undsoft** [comment]
@JounQin I'm personally not a fan of using snapshots in testing. I find them less readable and prone to abuse, but I suppose it's a matter of taste.
Otherwise changes look good.

**Pull request merged**
